/// <reference path="../src/types/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      id: 'instbackupsv100',
      name: 'instance_backups',
      type: 'base',
      system: false,
      fields: [
        {
          id: 'ibuser01',
          name: 'user',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'systemprofiles0',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ibinst01',
          name: 'instance',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'etae8tuiaxl6xfv',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ibkind01',
          name: 'kind',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['manual', 'pre-restore'],
        },
        {
          id: 'ibstatus1',
          name: 'status',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: true,
          maxSelect: 1,
          values: ['running', 'ready', 'failed'],
        },
        {
          id: 'ibfilename',
          name: 'filename',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: true,
          min: 0,
          max: 180,
          pattern: '',
        },
        {
          id: 'iblocalpa',
          name: 'localPath',
          type: 'text',
          system: false,
          hidden: true,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
        {
          id: 'ibremote',
          name: 'remoteKey',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
        {
          id: 'ibsize01',
          name: 'sizeBytes',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: null,
          max: null,
          onlyInt: true,
        },
        {
          id: 'ibcsize1',
          name: 'compressedBytes',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: null,
          max: null,
          onlyInt: true,
        },
        {
          id: 'ibsha256',
          name: 'checksum',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 80,
          pattern: '',
        },
        {
          id: 'iberr001',
          name: 'error',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
        {
          id: 'ibrerr01',
          name: 'remoteError',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
        {
          id: 'ibmanifest',
          name: 'manifest',
          type: 'json',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          maxSize: 2000000,
        },
      ],
      indexes: [
        'CREATE INDEX `idx_instance_backups_user` ON `instance_backups` (`user`)',
        'CREATE INDEX `idx_instance_backups_instance` ON `instance_backups` (`instance`)',
        'CREATE INDEX `idx_instance_backups_status` ON `instance_backups` (`status`)',
      ],
      listRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      viewRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('instbackupsv100')

    return app.delete(collection)
  }
)
