/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      id: 'ilstrreplv100',
      name: 'instance_litestream_replicas',
      type: 'base',
      system: false,
      fields: [
        {
          id: 'ilsuser01',
          name: 'user',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'systemprofiles0',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ilsinst01',
          name: 'instance',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'etae8tuiaxl6xfv',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ilsenabl',
          name: 'enabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: true,
        },
        {
          id: 'ilsstat1',
          name: 'status',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: true,
          maxSelect: 1,
          values: ['disabled', 'configured', 'running', 'failed', 'unavailable'],
        },
        {
          id: 'ilsrep01',
          name: 'replicaPath',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 500,
          pattern: '',
        },
        {
          id: 'ilssync1',
          name: 'syncInterval',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilsmon01',
          name: 'monitorInterval',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilsckpt1',
          name: 'checkpointInterval',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilssnap1',
          name: 'snapshotInterval',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilsret01',
          name: 'snapshotRetention',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilsval01',
          name: 'validationInterval',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 2,
          max: 16,
          pattern: '',
        },
        {
          id: 'ilsstart',
          name: 'lastStartedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ilsstop1',
          name: 'lastStoppedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ilscheck',
          name: 'lastCheckedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ilserror',
          name: 'lastError',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
      ],
      indexes: [
        'CREATE INDEX `idx_instance_litestream_replicas_user` ON `instance_litestream_replicas` (`user`)',
        'CREATE UNIQUE INDEX `idx_instance_litestream_replicas_instance` ON `instance_litestream_replicas` (`instance`)',
        'CREATE INDEX `idx_instance_litestream_replicas_enabled` ON `instance_litestream_replicas` (`enabled`)',
        'CREATE INDEX `idx_instance_litestream_replicas_status` ON `instance_litestream_replicas` (`status`)',
      ],
      listRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      viewRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('ilstrreplv100')
    return app.delete(collection)
  }
)
