/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const backups = app.findCollectionByNameOrId('instbackupsv100')
    const kind = backups.fields.getByName('kind')
    kind.values = ['manual', 'pre-restore', 'import', 'scheduled']
    app.save(backups)

    const collection = new Collection({
      id: 'ibpoliciesv100',
      name: 'instance_backup_policies',
      type: 'base',
      system: false,
      fields: [
        {
          id: 'ibpuser01',
          name: 'user',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'systemprofiles0',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ibpinst01',
          name: 'instance',
          type: 'relation',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          collectionId: 'etae8tuiaxl6xfv',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'ibpenabled',
          name: 'enabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: true,
        },
        {
          id: 'ibpcron01',
          name: 'cron',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: true,
          min: 3,
          max: 80,
          pattern: '',
        },
        {
          id: 'ibplocal',
          name: 'localEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'ibpremote',
          name: 'remoteEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'ibplcount',
          name: 'localRetentionCount',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 3650,
          onlyInt: true,
        },
        {
          id: 'ibpldays',
          name: 'localRetentionDays',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 3650,
          onlyInt: true,
        },
        {
          id: 'ibprcount',
          name: 'remoteRetentionCount',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 3650,
          onlyInt: true,
        },
        {
          id: 'ibprdays',
          name: 'remoteRetentionDays',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 3650,
          onlyInt: true,
        },
        {
          id: 'ibpactive',
          name: 'activeBehavior',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['stop-restart', 'skip-active'],
        },
        {
          id: 'ibplastat',
          name: 'lastStatus',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['never', 'running', 'ready', 'failed', 'skipped'],
        },
        {
          id: 'ibplastrun',
          name: 'lastRunAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ibplastok',
          name: 'lastSuccessAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ibplastbk',
          name: 'lastBackup',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 32,
          pattern: '',
        },
        {
          id: 'ibplaster',
          name: 'lastError',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 0,
          pattern: '',
        },
        {
          id: 'ibpdur01',
          name: 'lastDurationSeconds',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
      ],
      indexes: [
        'CREATE INDEX `idx_instance_backup_policies_user` ON `instance_backup_policies` (`user`)',
        'CREATE UNIQUE INDEX `idx_instance_backup_policies_instance` ON `instance_backup_policies` (`instance`)',
        'CREATE INDEX `idx_instance_backup_policies_enabled` ON `instance_backup_policies` (`enabled`)',
        'CREATE INDEX `idx_instance_backup_policies_status` ON `instance_backup_policies` (`lastStatus`)',
      ],
      listRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      viewRule: 'user = @request.auth.id || @request.auth.superAdmin = true',
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('ibpoliciesv100')
    app.delete(collection)

    const backups = app.findCollectionByNameOrId('instbackupsv100')
    const kind = backups.fields.getByName('kind')
    kind.values = ['manual', 'pre-restore', 'import']
    return app.save(backups)
  }
)
