/// <reference path="../src/types/types.d.ts" />
migrate(
  (app) => {
    const userRelation = (id) => ({
      id,
      name: 'user',
      type: 'relation',
      system: false,
      hidden: false,
      required: true,
      presentable: false,
      collectionId: 'systemprofiles0',
      cascadeDelete: true,
      minSelect: 0,
      maxSelect: 1,
    })
    const instanceRelation = (id) => ({
      id,
      name: 'instance',
      type: 'relation',
      system: false,
      hidden: false,
      required: true,
      presentable: false,
      collectionId: 'etae8tuiaxl6xfv',
      cascadeDelete: true,
      minSelect: 0,
      maxSelect: 1,
    })
    const createdField = (id) => ({
      id,
      name: 'created',
      type: 'autodate',
      system: false,
      hidden: false,
      presentable: false,
      onCreate: true,
      onUpdate: false,
    })
    const updatedField = (id) => ({
      id,
      name: 'updated',
      type: 'autodate',
      system: false,
      hidden: false,
      presentable: false,
      onCreate: true,
      onUpdate: true,
    })

    const policies = new Collection({
      id: 'instmonitorpol1',
      name: 'instance_monitoring_policies',
      type: 'base',
      system: false,
      fields: [
        userRelation('imonuser01'),
        instanceRelation('imoninst01'),
        {
          id: 'imonenable',
          name: 'enabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: true,
        },
        {
          id: 'imonhealth',
          name: 'healthEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imonhpath',
          name: 'healthPath',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 200,
          pattern: '',
        },
        {
          id: 'imonhfail',
          name: 'healthFailureCount',
          type: 'number',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 10,
          onlyInt: true,
        },
        {
          id: 'imoncpuen',
          name: 'cpuEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imoncputh',
          name: 'cpuThresholdPercent',
          type: 'number',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 100,
          onlyInt: false,
        },
        {
          id: 'imoncpudur',
          name: 'cpuSustainMinutes',
          type: 'number',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 60,
          onlyInt: true,
        },
        {
          id: 'imonmemen',
          name: 'memoryEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imonmemth',
          name: 'memoryThresholdPercent',
          type: 'number',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 100,
          onlyInt: false,
        },
        {
          id: 'imonmemdur',
          name: 'memorySustainMinutes',
          type: 'number',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 60,
          onlyInt: true,
        },
        {
          id: 'imonbacken',
          name: 'backupAlertsEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imonemail',
          name: 'emailEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imondiscen',
          name: 'discordEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imondiscurl',
          name: 'discordWebhook',
          type: 'text',
          system: false,
          hidden: true,
          required: false,
          presentable: false,
          min: 0,
          max: 2000,
          pattern: '',
        },
        {
          id: 'imonslacken',
          name: 'slackEnabled',
          type: 'bool',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
        },
        {
          id: 'imonslackurl',
          name: 'slackWebhook',
          type: 'text',
          system: false,
          hidden: true,
          required: false,
          presentable: false,
          min: 0,
          max: 2000,
          pattern: '',
        },
        {
          id: 'imonhstatus',
          name: 'lastHealthStatus',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['unknown', 'healthy', 'unhealthy', 'paused'],
        },
        {
          id: 'imonlastchk',
          name: 'lastCheckAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imongrace',
          name: 'graceUntil',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imonlastmet',
          name: 'lastMetricsAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imonhfstk',
          name: 'healthFailureStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonhsstk',
          name: 'healthSuccessStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonchstk',
          name: 'cpuHighStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imoncnstk',
          name: 'cpuNormalStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonmhstk',
          name: 'memoryHighStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonmnstk',
          name: 'memoryNormalStreak',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonlastcpu',
          name: 'lastCpuCapacityPercent',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: false,
        },
        {
          id: 'imonlastmem',
          name: 'lastMemoryPercent',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: false,
        },
        {
          id: 'imonlastlat',
          name: 'lastLatencyMs',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'imonlastcode',
          name: 'lastStatusCode',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 999,
          onlyInt: true,
        },
        {
          id: 'imonlasterr',
          name: 'lastError',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 500,
          pattern: '',
        },
        createdField('imoncreated'),
        updatedField('imonupdated'),
      ],
      indexes: [
        'CREATE UNIQUE INDEX `idx_instance_monitoring_policies_instance` ON `instance_monitoring_policies` (`instance`)',
        'CREATE INDEX `idx_instance_monitoring_policies_user` ON `instance_monitoring_policies` (`user`)',
        'CREATE INDEX `idx_instance_monitoring_policies_enabled` ON `instance_monitoring_policies` (`enabled`)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })
    app.save(policies)

    const checks = new Collection({
      id: 'insthealthchk1',
      name: 'instance_health_checks',
      type: 'base',
      system: false,
      fields: [
        userRelation('ihcuser01'),
        instanceRelation('ihcinst01'),
        {
          id: 'ihcchecked',
          name: 'checkedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'ihcresult',
          name: 'result',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['healthy', 'unhealthy'],
        },
        {
          id: 'ihclatency',
          name: 'latencyMs',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: true,
        },
        {
          id: 'ihcstatus',
          name: 'statusCode',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 999,
          onlyInt: true,
        },
        {
          id: 'ihcerrkind',
          name: 'errorKind',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['none', 'timeout', 'dns', 'tls', 'http', 'network', 'unknown'],
        },
        {
          id: 'ihcerror01',
          name: 'error',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 300,
          pattern: '',
        },
        createdField('ihccreated'),
      ],
      indexes: [
        'CREATE INDEX `idx_instance_health_checks_instance_checked` ON `instance_health_checks` (`instance`, `checkedAt` DESC)',
        'CREATE INDEX `idx_instance_health_checks_checked` ON `instance_health_checks` (`checkedAt`)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })
    app.save(checks)

    const incidents = new Collection({
      id: 'instmonincid1',
      name: 'instance_monitoring_incidents',
      type: 'base',
      system: false,
      fields: [
        userRelation('imiuser01'),
        instanceRelation('imiinst01'),
        {
          id: 'imitype01',
          name: 'type',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: true,
          maxSelect: 1,
          values: ['health', 'cpu', 'memory', 'backup'],
        },
        {
          id: 'imistatus',
          name: 'status',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['open', 'resolved'],
        },
        {
          id: 'imiopened',
          name: 'openedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imiresolved',
          name: 'resolvedAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imivalue01',
          name: 'value',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: false,
        },
        {
          id: 'imithresh',
          name: 'threshold',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: null,
          onlyInt: false,
        },
        {
          id: 'imimessage',
          name: 'message',
          type: 'text',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          min: 1,
          max: 1000,
          pattern: '',
        },
        {
          id: 'imidetails',
          name: 'details',
          type: 'json',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          maxSize: 100000,
        },
        {
          id: 'imisource',
          name: 'sourceId',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 64,
          pattern: '',
        },
        createdField('imicreated'),
        updatedField('imiupdated'),
      ],
      indexes: [
        'CREATE INDEX `idx_instance_monitoring_incidents_instance_opened` ON `instance_monitoring_incidents` (`instance`, `openedAt` DESC)',
        'CREATE INDEX `idx_instance_monitoring_incidents_active` ON `instance_monitoring_incidents` (`instance`, `status`, `type`)',
        'CREATE INDEX `idx_instance_monitoring_incidents_source` ON `instance_monitoring_incidents` (`instance`, `sourceId`)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })
    app.save(incidents)

    const deliveries = new Collection({
      id: 'instmondeliv1',
      name: 'instance_monitoring_deliveries',
      type: 'base',
      system: false,
      fields: [
        userRelation('imduser01'),
        instanceRelation('imdinst01'),
        {
          id: 'imdincident',
          name: 'incident',
          type: 'relation',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          collectionId: 'instmonincid1',
          cascadeDelete: true,
          minSelect: 0,
          maxSelect: 1,
        },
        {
          id: 'imdphase01',
          name: 'phase',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['opened', 'resolved', 'test'],
        },
        {
          id: 'imdchannel',
          name: 'channel',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['email', 'discord', 'slack'],
        },
        {
          id: 'imdstatus1',
          name: 'status',
          type: 'select',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSelect: 1,
          values: ['pending', 'sent', 'abandoned'],
        },
        {
          id: 'imdattempt',
          name: 'attempts',
          type: 'number',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 5,
          onlyInt: true,
        },
        {
          id: 'imdnextat',
          name: 'nextAttemptAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imdlastat',
          name: 'lastAttemptAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imddelivrd',
          name: 'deliveredAt',
          type: 'date',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: '',
          max: '',
        },
        {
          id: 'imdlasterr',
          name: 'lastError',
          type: 'text',
          system: false,
          hidden: false,
          required: false,
          presentable: false,
          min: 0,
          max: 1000,
          pattern: '',
        },
        {
          id: 'imdpayload',
          name: 'payload',
          type: 'json',
          system: false,
          hidden: false,
          required: true,
          presentable: false,
          maxSize: 100000,
        },
        createdField('imdcreated'),
        updatedField('imdupdated'),
      ],
      indexes: [
        'CREATE INDEX `idx_instance_monitoring_deliveries_pending` ON `instance_monitoring_deliveries` (`status`, `nextAttemptAt`)',
        'CREATE INDEX `idx_instance_monitoring_deliveries_instance_created` ON `instance_monitoring_deliveries` (`instance`, `created` DESC)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    return app.save(deliveries)
  },
  (app) => {
    for (const id of ['instmondeliv1', 'instmonincid1', 'insthealthchk1', 'instmonitorpol1']) {
      try {
        app.delete(app.findCollectionByNameOrId(id))
      } catch {}
    }
  }
)
